baseURL = "/"
copyright = "&copy;2018 Your Name"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
googleAnalytics = ""
languageCode = "en-US"
theme = "hugo-split-theme"
title = "Split - HTML Template Demo"
[params]
author = "Allen Djal"
description = "Brand Strategist, Digital Designer & Marketer, Creative Director, & Crazy One. "
favicon = ""
shareImage = "/uploads/allen-bw-web.jpg"
twitterHandle = "@allendjal"
[params.visual.image]
enable = true
file = "/uploads/allen-bw-web.jpg"
position = "center center"
[params.visual.video]
enable = false
file = "videos/background.mp4"
mute = true
[[params.links]]
[params.links.list1]
heading = "Connect"
[[params.links.list1.link]]
text = "Email"
url = "mailto:allen@fullstackdigital.com?subject=Hi%20There!"
[[params.links.list1.link]]
text = "Work"
url = "https://fullstackdigital.com/work/"
[[params.links.list1.link]]
text = "Blog"
url = "https://blog.fullstackdigital.com/@allendjal"
[params.links.list2]
heading = "Social"
[[params.links.list2.link]]
text = "Twitter"
url = "https://twitter.com/allendjal"
[[params.links.list2.link]]
text = "LinkedIn"
url = "https://www.linkedin.com/in/allendjal/"
[[params.links.list2.link]]
text = "Dribbble"
url = "https://dribbble.com/fullstackdigital"
[[params.links]]
[params.links.list2]
heading = ""
link = []
